### ISSUE TITLE
Code built in old version no longer works?

### ISSUE THREAD

**Issue by SpicyMelonCrab** [JujuAdams/Scribble#119]
Welp I had some autotype code that worked fine before on an older scribble version that I was trying to update to the new version, but now the text just completes immediately, skipping the autotype; and I can't figure out why?

So to be clear, the issue here is that the autotype event just 'skips', and when the dialogue first appears it is already complete. It doesn't play the callbackevent that is defined by scribble_autotype_function either... (I assume it is just skipping the whole 'autotype logic' for some reason. Any ideas?

STEP EVENT
-------------------
       if scribbleString == NULLVALUE{

            clipboard_set_text(myString); 
	    scribble_set_box_align(fa_left,fa_top); 
	    scribble_set_wrap(textAreaWidth, textAreaHeight);
	    scribble_set_starting_format("fnt_orbitron_black_12",c_white,fa_left); 
	    scribbleString = scribble_cache(myString);
	    scribble_autotype_fade_in(scribbleString, readSpeed,1,false, 0);
	    scribble_autotype_function(scribbleString, scribble_autotype_callback,SCRIBBLE_DEFAULT_OCCURANCE_NAME);
	    scribble_set_starting_format("fnt_orbitron_black_12",c_white,fa_center); 
	    scribbleName = scribble_cache(myName); 

       }

DRAW EVENT
-------------------
scribble_set_box_align(fa_left,fa_top); 
scribble_set_box_align(fa_left,fa_top); 
scribble_draw(_left + borderSize*1.5,_top + borderSize*1.5,scribbleString)

**Comment by JujuAdams** [comment]
`scribble_autotype_fade_in(scribbleString, readSpeed,1,false, 0);` is likely the issue here.

[`scribble_autotype_fade_in()`](https://github.com/JujuAdams/scribble/wiki/(6.0.0)-scribble_autotype_fade_in) uses the 5th optional argument to distinguish different occurrences\* of text. In this case, since you're specifying an occurrence, this argument should be left out (or set to `SCRIBBLE_DEFAULT_OCCURANCE_NAME`).

&nbsp;

\* I apologise for misspelling "occurrence" in literally 100% of the documentation

**Comment by SpicyMelonCrab** [comment]
Great, that did work!. but... the callback event doesn't seem to be playing like it did before...

**Comment by JujuAdams** [comment]
SpicyMelonCrab fixed the issue by undoing changes made to `__scribble_macros()` whilst updating Scribble
