### ISSUE TITLE
Default color feature request thing

### ISSUE THREAD

**Issue by DragoniteSpam** [JujuAdams/scribble#12]
I thought there used to be a "default color" macro, but I guess there's not?

[scribble_create, line 54](https://github.com/JujuAdams/scribble/blob/master/scripts/scribble_create/scribble_create.gml#L54) would instead be

    var _def_colour       = ((argument_count > 3) && (argument[3] != undefined))? argument[3] : SCRIBBLE_DEFAULT_COLOUR;

and somewhere in [__scribble_config](https://github.com/JujuAdams/scribble/blob/master/scripts/__scribble_config/__scribble_config.gml#L18) would be

    #macro SCRIBBLE_DEFAULT_COLOUR            c_white

**Comment by JujuAdams** [comment]
There was a default blend colour macro that was used when drawing but I removed that because 1) the config page was a bit intimidating 2) it's easy enough to modify scribble_draw() to do what you want.

However! Given this feedback I'll gladly implement a default vertex colour macro. That'll go live later today on `dev-4-x-x` and stable (`master`).
