### ISSUE TITLE
Figure out some way to improve autocomplete for methods

### ISSUE THREAD

**Issue by JujuAdams** [JujuAdams/Scribble#170]
Due to the GameMaker IDE having lacklustre autocomplete with struct methods, Scribble doesn't offer autocomplete for its methods. This makes using Scribble a bit fiddly and requires the user remember method arguments (or have the documentation open at the same time). This... isn't great.

There is a sorta solution available, and that's to use the `@func` JSDoc notation to add autocomplete for methods. This'll let us add usage hints for all methods. Unfortunately, these autocomplete hints are then global: every use of `draw`, even if it's usage is as a variable, will now be colour-coded as functions and will offer autocomplete as though the usage is a method/function.

A couple users have suggested using `@func` but I'm not convinced it's a good idea given how GM's autocomplete works. Opinions?

**Comment by ethanolsan** [comment]
I do agree that every keyword that aligns with a scribble method would be annoying and problematic at times, but I believe that the pros would outweigh the cons. Having the method arguments visible to the user would improve workflow and increase the user's knowledge of their scribble wisdom.

I personally didn't enjoy having to keep the scribble docs open while I used it, but I did learn to memorize many arguments. If this is how it has to be, then so be it I guess.

Here's a possible solution: though this might convolute things, it may work. Instead of naming many scribble functions the same as Game Maker functions, like draw, scribble functions could have an underscore before or after to differentiate between the two? I don't believe this would be an effective long term solution, but it may help till GMS receives proper support for method arguments.

**Comment by JujuAdams** [comment]
I wonder whether it'd be possible/feasible to ship method documentation as a separate script. This'd replace the `scribble_Methods` Note and, furthermore, would allow people to remove the `@func` metadata if they want.

**Comment by JujuAdams** [comment]
YAL pointed me towards https://github.com/GameMakerDiscord/GMEdit/wiki/Smart-completion

**Comment by JujuAdams** [comment]
Not something that I have the time or energy to address at this point.
