### ISSUE TITLE
Sprite origins

### ISSUE THREAD

**Issue by DragoniteSpam** [JujuAdams/scribble#21]
At this point I'm not sure if there's something wrong or if I'm just breaking everything I touch. Empty project, sprite alignment is "middle center," the alignment is set to `scribble_draw_set_box_align(fa_center, fa_middle)` and the yyz is attached.

If I had to take a guess this is a similar issue to #10 and #16 .

![image](https://user-images.githubusercontent.com/7087495/70842885-62cdbf00-1df7-11ea-90dc-4b24413f6309.png)

[internal-screaming.zip](https://github.com/JujuAdams/scribble/files/3963405/internal-screaming.zip)

**Comment by JujuAdams** [comment]
Taking a look at this now.

**Comment by JujuAdams** [comment]
mmok, first up you'll need to set `SCRIBBLE_ADD_SPRITE_ORIGINS` in `__scribble_config` to `true`. This is mentioned in passing in #16 so it's easy to see how you might have missed that. Unfortunately, to keep backwards compatibility with 5.x.x I had to default to `SCRIBBLE_ADD_SPRITE_ORIGINS` being `false`. For 6.x.x (which'll use all the fancy new features of GMS2.3.0) this macro will change to defaulting to `true`.

Setting up this config macro won't put the sprite at the position that you'd necessarily expect though, and this is due to how glyphs are defined by GameMaker and, by extension, how Scribble decides where to place glyphs. You'll need to fiddle with the origin a little bit to get the button to draw in the correct place, I found {0,15} to look pretty good in your use case.

**Comment by DragoniteSpam** [comment]
Urgh, for whatever reason the text alignment is now different with and without the icons. This was done with GMLive commenting and uncommenting the part of the code that appended the sprites to the scribble text.

![alignment](https://user-images.githubusercontent.com/7087495/70868662-d8996e00-1f50-11ea-8285-ca50da2bedde.gif)

All other things are equal, with the box align sent to `fa_center`, `fa_middle` and drawn at the final position of the center of the box.

For now it might be safe(r) for me to just draw the icons at their positions manually, or just rethink how the input bubble things work to begin with.

**Comment by JujuAdams** [comment]
Mmok, that's a different issue. The intent with Scribble is to make sprite insertion a painless process and clearly that's not the case. Let's fix 'er up!

**Comment by JujuAdams** [comment]
Spent some time today improving sprite handling. Sprites will now default to centring vertically on the line unless `SCRIBBLE_ADD_SPRITE_ORIGINS` is set to `true`, at which point the sprite's origin will affect the position of the sprite. Setting to sprite's origin to "Middle Centre" will replicate Scribble's default sprite positioning.

Hopefully this addresses the issues you've been having. Please reopen this issue if problems persist.
