### ISSUE TITLE
typewriter_ease() and typewriter_in() are not working as intended, even in the example .yyp

### ISSUE THREAD

**Issue by NoFluxGiven** [JujuAdams/Scribble#251]
typewriter_ease() does not function in the example .yyp and other projects as of GMS 2.3.7.603.

**Steps to Reproduce**
1. Clone the repository.
2. Open the project file.
3. Set the room order so that `rm_example` is run first.
4. Observe that `.typewriter_ease(SCRIBBLE_EASE.ELASTIC, 0, -25, 1, 1, 0, 0.1)` and the `smoothness` argument of `typewriter_in()` have no discernible effects. Changing the argument values of either function has no effect.

**Comment by JujuAdams** [comment]
What version of Scribble are you using?

**Comment by NoFluxGiven** [comment]
> What version of Scribble are you using?

7.1.2 :)

**Comment by NoFluxGiven** [comment]
**Update to this**: adding `typewriter_reset()` to any initialisation of a scribble element does fix this issue.

So as an example:

```
// Working version
element = scribble("[fa_center][fa_middle]"+_str)
    .typewriter_in(1, 10)
    .typewriter_ease(SCRIBBLE_EASE.CUBIC, 0, -5, 2, 1, 0, 0.4)
    .typewriter_reset() // if this is removed, typewriter_ease() and the smoothness argument of typewriter_in() have no effect (speed works as normal)
    .wrap(250)
```

Not sure if this is intended behaviour or not, so I'll leave it up to you on closing @JujuAdams.

**Comment by AtlaStar** [comment]
Just at a glance it appears that `tw_window_array` only calculates smoothing values it stores on a reset or when forced to update, as `typewriter_in` can't call a reset in the function as it sets the `tw_in` and `tw_do` to both to true just above checking, making the check always fail. 

This causes issues in the shader because the `fade` method uses `step` to later determine the max value between `f` and `result` with the latter being set to 0. Unfortunately until the smoothness value is applied to `tw_window_array` the second argument to `step` is always 0, meaning that the value of `time` in the main loop which performs the ease is always 0...which for all easing functions results in `time = 1 - 1` meaning it is still valued at 0 in the other functions which use that variable later.

Could be mistaken as I didn't dig into the code too hard, but that was what I was able to discern quickly @JujuAdams

**Comment by JujuAdams** [comment]
Spoiler warning: v8 will release soon
