### ISSUE TITLE
Remove scribble_draw_set_fade() from the API?

### ISSUE THREAD

**Issue by JujuAdams** [JujuAdams/scribble#36]
[`scribble_draw_set_fade()`](https://github.com/JujuAdams/scribble/wiki/scribble_draw_set_fade) is a legacy function left over from previous versions on Scribble. I can't imagine it gets much use.

**Comment by DragoniteSpam** [comment]
I completely forgot it was even there, to be honest.

**Comment by JujuAdams** [comment]
Removed in v6

**Comment by JujuAdams** [comment]
Reopening for discussion.

**Comment by AvioxArcade** [comment]
I primarily am using `scribble_draw_set_fade()` because the (likely old) example I found somewhere was using it. 

But another useful option for it that might not exist with 'autotype' functions is direct per-character control of typing speed. For example, if the next character of the text is a period or other punctuation, you can slow down the position incrementation.
Is this possible with autotype?

**Comment by JujuAdams** [comment]
It *is* possible, but it's not convenient!

People have asked for a `[delay]` and `[pause]` native tag so I really do need to get around to that.
