### ISSUE TITLE
font_bake_shadow() increases the width of space characters

### ISSUE THREAD

**Issue by KingDevyn** [JujuAdams/Scribble#525]
Using font_bake_shadow() adds length to the space character equal in pixels to the value of the dX argument.

**Comment by JujuAdams** [comment]
Debating internally whether this is desirable or not.

**Comment by KingDevyn** [comment]
I would prefer it be optional if included. I guess I can always manually set the length of the space character to be X pixels shorter for baked fonts as a workaround though.

**Comment by JujuAdams** [comment]
Yeah the question is what is the expected default behaviour is.

**Comment by KingDevyn** [comment]
In Adobe After Effects, Premier, Photoshop this behavior doesn't exist. I'm not aware of any design software where drop shadows behave in such a way.

**Comment by JujuAdams** [comment]
Scribble isn't design software. The decision needs to be made based on what a game developer wants/needs.

**Comment by KingDevyn** [comment]
Just adding input for what's expected default behavior.

**Comment by JujuAdams** [comment]
Reviewed the code and there's nothing in there that intentionally spaces things out. I dived a little deeper and it turns out that I was calculating space widths using the wrong property. You can find patches here:
v9 - https://github.com/JujuAdams/Scribble/commit/611bbe50250bf75f07c4f5566b2e8d46009098ce
v8 - https://github.com/JujuAdams/Scribble/commit/0b29f3e7d8d65dbca971c66e3e2b1aaeae0daec6
