### ISSUE TITLE
Missing docs for .preprocessor()

### ISSUE THREAD

**Issue by Grisgram** [JujuAdams/Scribble#557]
What exactly does this do? At the moment there's no 9.1 documentation available at the docs website.

Just curious. I saw the description about variables and things that might change, a bit more detail would be great how this new group of functions works.
unfortunately the server is read only (at least for me, others seem to have the permission to write there, but for me it's locked), so i have to ask here

thanks!

**Comment by JujuAdams** [comment]
`.preprocessor()` is a text element-scoped method. That means every text element created by `scribble()` has access to it. `.preprocessor()` is a **regenerator** method so changing the input value will trigger a regeneration of the underlying text model.

A preprocessor function allows you to adjust a string being drawn by Scribble using custom code that goes beyond what Scribble can natively employ. A preprocessor function takes one argument which is the input string defined when calling `scribble()`. This string is literally the string passed to `scribble()` so it will include command tags. A preprocessor function will need to return the modified string using the standard `return` command. The preprocessor function is called before Scribble macros are evaluated.

The preprocessor function is called before Scribble does any processing. It is also called once when a text element is first cached. This means that using a preprocessor to draw a variable that is liable to update during the lifetime of a text element will not lead to sastisfactory results. Because the preprocessor function is called when the text element is cached, the value that is found in the variable is "frozen" into the text model and will not change until the text element is regenerated by some means. *(If you want to have live updating variables, just modify the input string like you would with any other normal text drawing command.)*

The intention is that you can modify an input string using whatever wacky string manipulation that you want before Scribble starts its parser. This feature came as a response to [this feature request](https://github.com/JujuAdams/Scribble/issues/555). There are many things I can't support as a general feature but I can give people the tools to invent their own methodologies.

An example pass-through preprocessor function (a function that does not modify the string) looks like this:

```gml
function(_string)
{
    return _string;
}
```

A preprocessor function that replaces `$123$` to follow the pattern `[spr_money][c_green]123[/c]` looks like this:

```gml
function(_string)
{
    var _split = string_split(_string, "$");
    var _i = array_length(_split)-2;
    repeat((array_length(_split)-1) div 2)
    {
        array_insert(_split, _i,   "[spr_money][c_green]");
        array_insert(_split, _i+1, "[/c]");
        _i -= 2;
    }
    
    return string_concat_ext(_split);
}
```

As an exercise for the reader, consider how the text colour could change to red if the amount of money is negative.

Without intervention, a text element will use the global default preprocessor function. This can be set by `scribble_default_preprocessor_set()`. Updating the global default preprocessor function will **not** automatically regenerate existing text elements so be careful how you use it (intention is to set-and-forget when the game starts).

The method `.preprocessor()` itself takes one argument - the function - and that will set a preprocessor function for the scoped Scribble text element. Changing the function being used as the preprocessor with `.preprocessor()` will regenerate the text model. For the avoidance of doubt, calling the `.preprocessor()` method will override the global default. They don't stack. If you'd like to restore global default behaviour, you can call `.preprocessor(undefined)`. If you'd like to override everything and strictly use a pass-through preprocessor, you can use `.preprocessor(SCRIBBLE_NO_PREPROCESS)` (which is a macro for the pass-through function above).

**Comment by Grisgram** [comment]
This is _extremely helpful_, a great addition and wonderful documented!

Thanks a lot, juju!

**Comment by JujuAdams** [comment]
Wait a second I haven't actually done the work.
